#! /bin/sh

bspc monitor HDMI-A-0 -d 1 web game chat music 6 7 8 9 10
bspc monitor eDP -d 1 2 3 4 5 6 7 8 9 10
pgrep -x sxhkd > /dev/null || sxhkd &

flameshot &
dunst &
otd &
picom &
$HOME/.config/polybar/launch.sh
feh --bg-fill $HOME/.wallpapers/1624152287461.png

gsettings set org.gnome.desktop.wm.preferences button-layout "" &

# Config

bspc config ignore_ewmh_struts true
bspc config border_width         3
bspc config window_gap           3
bspc config top_padding          30
bspc config normal_border_color "#0A0D0F"
bspc config active_border_color "#0A0D0F"
bspc config focused_border_color "#5D3FD3"
bspc config focus_follows_pointer       true

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Rules

bspc rule -a osu!.exe desktop=^3
bspc rule -a discord desktop=^4
bspc rule -a firefox desktop=^2

# Extra

xsetroot -cursor_name left_ptr &
setxkbmap -model pc104 -layout gb,gb -variant dvorak,