#! /bin/sh
xrandr --output HDMI-A-0 --mode 1920x1080 --rate 144.00 --left-of eDP --primary --output eDP --mode 1920x1080 --rate 60
bspc monitor HDMI-A-0 -d 1 web game chat music 6 7 8 cum ""
bspc monitor eDP -d 1 web game chat music 6 7 8 9 10
pgrep -x sxhkd > /dev/null || sxhkd &
picom -b --experimental-backend &
nitrogen --set-auto ~/.wallpapers/quints.jpg --head=1
nitrogen --set-auto ~/.wallpapers/rem.png --head=0
~/.config/polybar/launch.sh
polybar bar1 &
polybar bar2 &
unclutter &
flameshot &
dunst &
# exec ~/.nix-profile/libexec/polkit-gnome-authentication-agent-1
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
bspc config ignore_ewmh_struts true
bspc config border_width         3
bspc config window_gap           5
bspc config top_padding          32
bspc config normal_border_color "#000000"
bspc config focused_border_color "#5D3FD3"
bspc config normal_urgent_color "#ff0000"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

xsetroot -cursor_name left_ptr &

bspc rule -a osu!.exe desktop=^3
bspc rule -a discord desktop=^4
bspc rule -a firefox desktop=^2

setxkbmap -model pc104 -layout gb,us,gb -variant dvorak,colemak_dh
